apiVersion: v1
kind: Pod
metadata:
  name: frontend-stress-test
  namespace: frontend
spec:
  containers:
  - name: wrk
    image: williamyeh/wrk
    command: ["/bin/sh", "-c"]
    args: 
      - |
        while true; do
          wrk -t2 -c100 -d30s http://frontend-svc
          sleep 1
        done