apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: backend
  labels:
    name: backend
spec: {}
status: {}

---

apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: database
  labels:
    name: database
spec: {}
status: {}

---

apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: external-api
  labels:
    name: external-api
spec: {}
status: {}

---

apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: frontend
  labels:
    name: frontend
spec: {}
status: {}
